from lz import *

confs = [
    # edict(
    #     arch='resnet',
    #     depth=44,
    #     epochs=125,
    #     schedule=[80, 120],
    #     gamma=0.1,
    #     wd=1e-4,
    #     checkpoint='work/conv.neck1',
    #     resume='',
    #     evaluate=False,
    #     conv_op='nn.Conv2d',
    #     bottleneck='Bottleneck',
    #
    # ),
    # edict(
    #     arch='resnet',
    #     depth=44,
    #     epochs=125,
    #     schedule=[80, 120],
    #     gamma=0.1,
    #     wd=1e-4,
    #     checkpoint='work/c1conv.neck2',
    #     resume='',
    #     evaluate=False,
    #     conv_op='C1Conv',
    #     bottleneck='Bottleneck2',
    #
    # ),
    # edict(
    #     arch='resnet',
    #     depth=44,
    #     epochs=125,
    #     schedule=[80, 120],
    #     gamma=0.1,
    #     wd=1e-4,
    #     checkpoint='work/tc1conv.neck2',
    #     resume='',
    #     evaluate=False,
    #     conv_op='TC1Conv',
    #     bottleneck='Bottleneck2',
    # ),
    # edict(
    #     arch='resnet',
    #     depth=44,
    #     epochs=125,
    #     schedule=[80, 120],
    #     gamma=0.1,
    #     wd=1e-4,
    #     checkpoint='work/c1conv.neck1',
    #     resume='',
    #     evaluate=False,
    #     conv_op='C1Conv',
    #     bottleneck='Bottleneck',
    # ),
    # edict(
    #     arch='resnet',
    #     depth=44,
    #     epochs=125,
    #     schedule=[80, 120],
    #     gamma=0.1,
    #     wd=1e-4,
    #     checkpoint='work/c1c1conv.neck2',
    #     resume='',
    #     evaluate=False,
    #     conv_op='C1C1Conv',
    #     bottleneck='Bottleneck2',
    # ),
    # edict(
    #     arch='resnet',
    #     depth=44,
    #     epochs=125,
    #     schedule=[80, 120],
    #     gamma=0.1,
    #     wd=1e-4,
    #     checkpoint='work/c1c1conv.neck1',
    #     resume='',
    #     evaluate=False,
    #     conv_op='C1C1Conv',
    #     bottleneck='Bottleneck',
    # ),


    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/zpc1conv.neck2',
        resume='',
        evaluate=False,
        conv_op='ZPC1Conv',
        bottleneck='Bottleneck2'
    ),
    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/zpc1conv.9.neck2',
        resume='',
        evaluate=False,
        conv_op='ZPC1Conv',
        bottleneck='Bottleneck2',
        meta_stride=1
    ),


    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/tc1conv.neck1',
        resume='',
        evaluate=False,
        conv_op='TC1Conv',
        bottleneck='Bottleneck',

    ),
    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/zpc1conv.neck1',
        resume='',
        evaluate=False,
        conv_op='ZPC1Conv',
        bottleneck='Bottleneck'
    ),
    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/zpc1conv.9.neck1',
        resume='',
        evaluate=False,
        conv_op='ZPC1Conv',
        bottleneck='Bottleneck',
        meta_stride=1
    ),
    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/tc1conv.neck1.comp4',
        resume='',
        evaluate=False,
        conv_op='TC1Conv',
        bottleneck='Bottleneck',
        comp=4,
    ),
    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/zpc1conv.neck1.comp4',
        resume='',
        evaluate=False,
        conv_op='ZPC1Conv',
        bottleneck='Bottleneck',
        comp=4.
    ),
    edict(
        arch='resnet',
        depth=44,
        epochs=125,
        schedule=[80, 120],
        gamma=0.1,
        wd=1e-4,
        checkpoint='work/zpc1conv.9.neck1.comp4',
        resume='',
        evaluate=False,
        conv_op='ZPC1Conv',
        bottleneck='Bottleneck',
        meta_stride=1,
        comp=4,
    ),
]
print(len(confs))
chs = int("$CHS")
conf = confs[chs]
with open(conf.checkpoint + '.chs', 'w') as f:
    f.write('model {} use conf chs {} \n'.format(conf.checkpoint, chs))
